### PR TITLE
Update fixtures from forge when the module version doesn't match; fix git < 2.7 compatibility

### PR DESCRIPTION
**Pull request by nabertrand**
This commit ensures that already-installed forge modules match the requested version and also provides compatibility with git versions < 2.7 (when `-C` was added).

### CODE REVIEW

**Comment by daianamezdrea** [comment]
Hi @nabertrand, can you rebase this PR ? I would like to review it with the team. Thank you! Cheers!

**Comment by nabertrand** [comment]
Hi @daianamezdrea, I will try and rebase this shortly.

**Comment by DavidS** [comment]
Rebased to see where the tests lead us today

**Comment by DavidS** [comment]
Fix for those ruby/codecov errors in #233

**Pull request merged**
