### PR TITLE
Use faster shallow git clone

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by tphoney** [comment]
what kind of speed up did you see with this ? are there any potential side effects ?

**Comment by sbadia** [comment]
Hi :+1: for this!
* Concerning speed-up, it's pretty the same on little repos (but faster in case of a repo with a big history).

Without depth param.
```bash
❯ time git clone git://github.com/puppetlabs/puppet.git
Cloning into 'puppet'...
remote: Counting objects: 186943, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 186943 (delta 0), reused 0 (delta 0), pack-reused 186932
Receiving objects: 100% (186943/186943), 44.75 MiB | 284.00 KiB/s, done.
Resolving deltas: 100% (135653/135653), done.
Checking connectivity... done.
git clone git://github.com/puppetlabs/puppet.git  6.13s user 2.21s system 6% cpu 2:10.20 total
```
 Vs with depth param.
```bash
❯ time git clone --depth 1 git://github.com/puppetlabs/puppet.git 
Cloning into 'puppet'...
remote: Counting objects: 3530, done.
remote: Compressing objects: 100% (2984/2984), done.
remote: Total 3530 (delta 316), reused 1617 (delta 240), pack-reused 0
Receiving objects: 100% (3530/3530), 3.19 MiB | 1.13 MiB/s, done.
Resolving deltas: 100% (316/316), done.
Checking connectivity... done.
git clone --depth 1 git://github.com/puppetlabs/puppet.git  0.19s user 0.16s system 7% cpu 4.813 total
```

* Concerning potential side-effects, I think nothing, `depth 1` fetch only the latest version so we don't have the full history in the cloned repo, but it's a fixture, not a clone used for development.

**Comment by hunner** [comment]
Cool. I'll get it rebased then.

**Comment by hunner** [comment]
Merged #94

**Pull request closed without merging**
