### PR TITLE
Allow injecting options for metadata-json-lint

### PR DESCRIPTION
**Pull request by felixb**
This allows running `metadata-json-lint` with `--no-strict-license` or `--no-fail-on-warnings`.

### CODE REVIEW

**Comment by DavidS** [comment]
I'd rather see this replaced by using the linter's raketask https://github.com/voxpupuli/metadata-json-lint/blob/master/lib/metadata-json-lint/rake_task.rb ; then you can just set options in your Rakefile (see https://github.com/voxpupuli/metadata-json-lint/blob/master/lib/metadata_json_lint.rb#L6-L24) using your setup as you like

**Comment by felixb** [comment]
We now try to require the gem and invoke the original rake task as suggested.
Setting options is working fine.

Thanks for the hint. :+1:

**Comment by DavidS** [comment]
Excellent. Thanks!

**Comment by garethr** [comment]
So, this broke the API for the rake tasks in a minor version bump :( The task names are basically a public API given how rakefiles work. Also this change was not mentioned in the Changelog (which also states the module follows semver).

The change from metadata to metadata_lint is backwards incompatible, and anyone not pinning to a specific version is about to find all their tests fail without local changes.

I'd recommend pushing a backwards incompatible shim, if you really want with a warning that metadata is deprecated and you should use metadata_lint.

cc. @hunner @bmjen

**Pull request merged**
