### PR TITLE
update README

### PR DESCRIPTION
**Pull request by b4ldr**
small documentation updated, i am curios, why limit functionality to just three tiers .

### CODE REVIEW

**Comment by DavidS** [comment]
cc @ThoughtCrhyme for the question.

**Comment by ThoughtCrhyme** [comment]
@b4ldr Hi John, we use three tiers because our internal testing happens in three cadences: per PR, nightly, and weekly corresponding to "high", "medium" and "low" tiers.

**Comment by b4ldr** [comment]
@ThoughtCrhyme it would be useful to be able to use arbitrary tiers here, would you be open to removing the constraint on these keywords or making it possible to configure the [checking array](https://github.com/puppetlabs/puppetlabs_spec_helper/blob/master/lib/puppetlabs_spec_helper/tasks/beaker.rb#L70).  I would be happy to create a PR if your open to it

**Comment by ThoughtCrhyme** [comment]
@b4ldr we'd be happy to review any PR's that make it easier to run the acceptance tests at arbitrary test tiers.

**Pull request merged**
