### PR TITLE
Add more beaker actions

### PR DESCRIPTION
**Pull request by dmitryilyin**
* Renamed beaker_nodes to beaker:sets
  Old name aliaced to the new one.
* Add beaker:ssh action to login to the node
* For every node set add beaker:$set action to
  run the tests for this set and beaker:ssh:$set
  to login to this test node

### CODE REVIEW

**Comment by DavidS** [comment]
@zreichert , @gregohardy : please review interface here

**Comment by dmitryilyin** [comment]
ping

**Comment by DavidS** [comment]
This overlaps with [rototiller](https://github.com/puppetlabs/rototiller), a replacement for this part of PSH, perhaps @er0ck can direct some attention on this?

**Comment by dmitryilyin** [comment]
Hmm, this **rototiller** looks very nice and promising.
Looks like it's still in an early stage of development but **puppetlabs_spec_helper** is being used pretty much everywhere.
Perhaps, I could help with **rototiller** instead?

**Comment by dmitryilyin** [comment]
Maybe **puppetlabs_spec_helper** can be refactored to use **rototiller** for rake tasks generation?

**Comment by DavidS** [comment]
@dmitryilyin using rototiller as new base for PSH would be the plan, once a stable release is out. I can't make any promises at the current time though, and all rototiller folks are on PDX timezone, so asleep for another five hours.

**Comment by er0ck** [comment]
rototiller's user stories, as of now, do not exactly cover what it appears these tasks are for.  They will make writing these tasks easier and more uniform, sometime soon.  The first release of rototiller, which we expect very soon, is primarily geared at environment variable tracking and messaging and tasks with commands and their flags (with environment variable linking/override)
We may want to investigate the value of centralizing a task for things like `beaker:nodes` as above.

**Comment by dmitryilyin** [comment]
Maybe we can merge this PR and refactor env variable related stuff to rototiller later?

**Comment by er0ck** [comment]
@DavidS i'd suggest what @dmitryilyin said, solely with regards to any future Rototiller related execution.

**Comment by DavidS** [comment]
Thanks everyone for their input!

**Pull request merged**
